// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjHmTpMwqM5IHIWj24WidTeZBy3CBPvEk',
    appId: '1:537021299938:web:cc0c37a3ea43732c98b2bb',
    messagingSenderId: '537021299938',
    projectId: 'flutter-ifsp',
    authDomain: 'flutter-ifsp.firebaseapp.com',
    storageBucket: 'flutter-ifsp.firebasestorage.app',
    measurementId: 'G-7FGFJPC4GX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtV-CqXnPplep3rBa4Ns-3cNk7iX1JUug',
    appId: '1:537021299938:android:4b39785804be859198b2bb',
    messagingSenderId: '537021299938',
    projectId: 'flutter-ifsp',
    storageBucket: 'flutter-ifsp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKw-hdjpjJvC6tcyxb_KBXQMQtqi688IQ',
    appId: '1:537021299938:ios:624d13b17a2f003c98b2bb',
    messagingSenderId: '537021299938',
    projectId: 'flutter-ifsp',
    storageBucket: 'flutter-ifsp.firebasestorage.app',
    iosBundleId: 'com.example.nomeDoProjeto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKw-hdjpjJvC6tcyxb_KBXQMQtqi688IQ',
    appId: '1:537021299938:ios:624d13b17a2f003c98b2bb',
    messagingSenderId: '537021299938',
    projectId: 'flutter-ifsp',
    storageBucket: 'flutter-ifsp.firebasestorage.app',
    iosBundleId: 'com.example.nomeDoProjeto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjHmTpMwqM5IHIWj24WidTeZBy3CBPvEk',
    appId: '1:537021299938:web:efb74c03d83a858798b2bb',
    messagingSenderId: '537021299938',
    projectId: 'flutter-ifsp',
    authDomain: 'flutter-ifsp.firebaseapp.com',
    storageBucket: 'flutter-ifsp.firebasestorage.app',
    measurementId: 'G-2HRKWMRPWS',
  );
}
